name:                stateful-graph-algos
version:             0.1.0.0
github:              "dougissi/stateful-graph-algos"
license:             BSD3
author:              "Douglas Issichopoulos"
maintainer:          "doi4@illinois.edu"
copyright:           "2023 Douglas Issichopoulos"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dougissi/stateful-graph-algos#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  stateful-graph-algos-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stateful-graph-algos

tests:
  stateful-graph-algos-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stateful-graph-algos
    - HUnit >= 1.5
